package amw.statki.model;
// Generated Jul 15, 2019 1:41:18 PM by Hibernate Tools 5.1.7.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Rejs generated by hbm2java
 */
@Entity
@Table(name = "Rejs", schema = "dbo", catalog = "Statki")
public class Rejs implements java.io.Serializable {

	private Integer id;
	private Port portByPortCelId;
	private Port portByPortPoczId;
	private Statek statek;
	private Date startPlan;
	private Date startFakt;
	private Date koniecFakt;
	private String opis;
	private Date koniecPlan;

	public Rejs() {
	}

	public Rejs(Date startPlan, Date startFakt, Date koniecFakt) {
		this.startPlan = startPlan;
		this.startFakt = startFakt;
		this.koniecFakt = koniecFakt;
	}

	public Rejs(Port portByPortCelId, Port portByPortPoczId, Statek statek, Date startPlan, Date startFakt,
			Date koniecFakt, String opis, Date koniecPlan) {
		this.portByPortCelId = portByPortCelId;
		this.portByPortPoczId = portByPortPoczId;
		this.statek = statek;
		this.startPlan = startPlan;
		this.startFakt = startFakt;
		this.koniecFakt = koniecFakt;
		this.opis = opis;
		this.koniecPlan = koniecPlan;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Port_Cel_ID")
	public Port getPortByPortCelId() {
		return this.portByPortCelId;
	}

	public void setPortByPortCelId(Port portByPortCelId) {
		this.portByPortCelId = portByPortCelId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Port_Pocz_ID")
	public Port getPortByPortPoczId() {
		return this.portByPortPoczId;
	}

	public void setPortByPortPoczId(Port portByPortPoczId) {
		this.portByPortPoczId = portByPortPoczId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Statek_ID")
	public Statek getStatek() {
		return this.statek;
	}

	public void setStatek(Statek statek) {
		this.statek = statek;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "start_plan", nullable = false, length = 23)
	public Date getStartPlan() {
		return this.startPlan;
	}

	public void setStartPlan(Date startPlan) {
		this.startPlan = startPlan;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "start_fakt", nullable = false, length = 23)
	public Date getStartFakt() {
		return this.startFakt;
	}

	public void setStartFakt(Date startFakt) {
		this.startFakt = startFakt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "koniec_fakt", nullable = false, length = 23)
	public Date getKoniecFakt() {
		return this.koniecFakt;
	}

	public void setKoniecFakt(Date koniecFakt) {
		this.koniecFakt = koniecFakt;
	}

	@Column(name = "opis", length = 150)
	public String getOpis() {
		return this.opis;
	}

	public void setOpis(String opis) {
		this.opis = opis;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "koniec_plan", length = 23)
	public Date getKoniecPlan() {
		return this.koniecPlan;
	}

	public void setKoniecPlan(Date koniecPlan) {
		this.koniecPlan = koniecPlan;
	}

}
