package amw.statki.model;
// Generated Jul 15, 2019 1:41:18 PM by Hibernate Tools 5.1.7.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Towar generated by hbm2java
 */
@Entity
@Table(name = "Towar", schema = "dbo", catalog = "Statki")
public class Towar implements java.io.Serializable {

	private int id;
	private Port port;
	private Statek statek;
	private String nrListu;
	private String nazwa;
	private String lokalizacja;
	private BigDecimal ilosc;
	private String opis;
	private Set<TransportTowaru> transportTowarus = new HashSet<TransportTowaru>(0);

	public Towar() {
	}

	public Towar(int id, Port port, Statek statek) {
		this.id = id;
		this.port = port;
		this.statek = statek;
	}

	public Towar(int id, Port port, Statek statek, String nrListu, String nazwa, String lokalizacja, BigDecimal ilosc,
			String opis, Set<TransportTowaru> transportTowarus) {
		this.id = id;
		this.port = port;
		this.statek = statek;
		this.nrListu = nrListu;
		this.nazwa = nazwa;
		this.lokalizacja = lokalizacja;
		this.ilosc = ilosc;
		this.opis = opis;
		this.transportTowarus = transportTowarus;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Port_Pocz_ID", nullable = false)
	public Port getPort() {
		return this.port;
	}

	public void setPort(Port port) {
		this.port = port;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Port_Cel_ID", nullable = false)
	public Statek getStatek() {
		return this.statek;
	}

	public void setStatek(Statek statek) {
		this.statek = statek;
	}

	@Column(name = "nr_listu", length = 32)
	public String getNrListu() {
		return this.nrListu;
	}

	public void setNrListu(String nrListu) {
		this.nrListu = nrListu;
	}

	@Column(name = "nazwa", length = 20)
	public String getNazwa() {
		return this.nazwa;
	}

	public void setNazwa(String nazwa) {
		this.nazwa = nazwa;
	}

	@Column(name = "lokalizacja", length = 50)
	public String getLokalizacja() {
		return this.lokalizacja;
	}

	public void setLokalizacja(String lokalizacja) {
		this.lokalizacja = lokalizacja;
	}

	@Column(name = "ilosc", precision = 28, scale = 0)
	public BigDecimal getIlosc() {
		return this.ilosc;
	}

	public void setIlosc(BigDecimal ilosc) {
		this.ilosc = ilosc;
	}

	@Column(name = "opis", length = 100)
	public String getOpis() {
		return this.opis;
	}

	public void setOpis(String opis) {
		this.opis = opis;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "towar")
	public Set<TransportTowaru> getTransportTowarus() {
		return this.transportTowarus;
	}

	public void setTransportTowarus(Set<TransportTowaru> transportTowarus) {
		this.transportTowarus = transportTowarus;
	}

}
