package amw.statki.model;
// Generated Jul 15, 2019 1:41:18 PM by Hibernate Tools 5.1.7.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TransportTowaruId generated by hbm2java
 */
@Embeddable
public class TransportTowaruId implements java.io.Serializable {

	private int towarId;
	private int statekId;

	public TransportTowaruId() {
	}

	public TransportTowaruId(int towarId, int statekId) {
		this.towarId = towarId;
		this.statekId = statekId;
	}

	@Column(name = "Towar_ID", nullable = false)
	public int getTowarId() {
		return this.towarId;
	}

	public void setTowarId(int towarId) {
		this.towarId = towarId;
	}

	@Column(name = "Statek_ID", nullable = false)
	public int getStatekId() {
		return this.statekId;
	}

	public void setStatekId(int statekId) {
		this.statekId = statekId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TransportTowaruId))
			return false;
		TransportTowaruId castOther = (TransportTowaruId) other;

		return (this.getTowarId() == castOther.getTowarId()) && (this.getStatekId() == castOther.getStatekId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getTowarId();
		result = 37 * result + this.getStatekId();
		return result;
	}

}
