package amw.statki.model;
// Generated Jul 15, 2019 1:41:18 PM by Hibernate Tools 5.1.7.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TransportTowaru generated by hbm2java
 */
@Entity
@Table(name = "Transport_towaru", schema = "dbo", catalog = "Statki")
public class TransportTowaru implements java.io.Serializable {

	private TransportTowaruId id;
	private Port port;
	private Statek statekByPortCelId;
	private Statek statekByStatekId;
	private Towar towar;
	private Date startPlan;
	private Date koniecPlan;
	private Date startFakt;
	private Date koniecFakt;
	private String lokalizacja;
	private String uwagi;

	public TransportTowaru() {
	}

	public TransportTowaru(TransportTowaruId id, Statek statekByStatekId, Towar towar, Date startPlan,
			Date koniecPlan) {
		this.id = id;
		this.statekByStatekId = statekByStatekId;
		this.towar = towar;
		this.startPlan = startPlan;
		this.koniecPlan = koniecPlan;
	}

	public TransportTowaru(TransportTowaruId id, Port port, Statek statekByPortCelId, Statek statekByStatekId,
			Towar towar, Date startPlan, Date koniecPlan, Date startFakt, Date koniecFakt, String lokalizacja,
			String uwagi) {
		this.id = id;
		this.port = port;
		this.statekByPortCelId = statekByPortCelId;
		this.statekByStatekId = statekByStatekId;
		this.towar = towar;
		this.startPlan = startPlan;
		this.koniecPlan = koniecPlan;
		this.startFakt = startFakt;
		this.koniecFakt = koniecFakt;
		this.lokalizacja = lokalizacja;
		this.uwagi = uwagi;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "towarId", column = @Column(name = "Towar_ID", nullable = false)),
			@AttributeOverride(name = "statekId", column = @Column(name = "Statek_ID", nullable = false)) })
	public TransportTowaruId getId() {
		return this.id;
	}

	public void setId(TransportTowaruId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Port_Pocz_ID")
	public Port getPort() {
		return this.port;
	}

	public void setPort(Port port) {
		this.port = port;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Port_Cel_ID")
	public Statek getStatekByPortCelId() {
		return this.statekByPortCelId;
	}

	public void setStatekByPortCelId(Statek statekByPortCelId) {
		this.statekByPortCelId = statekByPortCelId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Statek_ID", nullable = false, insertable = false, updatable = false)
	public Statek getStatekByStatekId() {
		return this.statekByStatekId;
	}

	public void setStatekByStatekId(Statek statekByStatekId) {
		this.statekByStatekId = statekByStatekId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Towar_ID", nullable = false, insertable = false, updatable = false)
	public Towar getTowar() {
		return this.towar;
	}

	public void setTowar(Towar towar) {
		this.towar = towar;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "start_plan", nullable = false, length = 23)
	public Date getStartPlan() {
		return this.startPlan;
	}

	public void setStartPlan(Date startPlan) {
		this.startPlan = startPlan;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "koniec_plan", nullable = false, length = 23)
	public Date getKoniecPlan() {
		return this.koniecPlan;
	}

	public void setKoniecPlan(Date koniecPlan) {
		this.koniecPlan = koniecPlan;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "start_fakt", length = 23)
	public Date getStartFakt() {
		return this.startFakt;
	}

	public void setStartFakt(Date startFakt) {
		this.startFakt = startFakt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "koniec_fakt", length = 23)
	public Date getKoniecFakt() {
		return this.koniecFakt;
	}

	public void setKoniecFakt(Date koniecFakt) {
		this.koniecFakt = koniecFakt;
	}

	@Column(name = "lokalizacja", length = 50)
	public String getLokalizacja() {
		return this.lokalizacja;
	}

	public void setLokalizacja(String lokalizacja) {
		this.lokalizacja = lokalizacja;
	}

	@Column(name = "uwagi", length = 150)
	public String getUwagi() {
		return this.uwagi;
	}

	public void setUwagi(String uwagi) {
		this.uwagi = uwagi;
	}

}
