-- Generated by Oracle SQL Developer Data Modeler 19.1.0.081.0911
--   at:        2019-07-08 10:15:57 CEST
--   site:      SQL Server 2012
--   type:      SQL Server 2012


BEGIN TRANSACTION

CREATE TABLE Port 
    (
     ID INTEGER IDENTITY(1,1) NOT NULL PRIMARY KEY, 
     nazwa VARCHAR (25) NOT NULL , 
     skrot CHAR (5) NOT NULL , 
     la FLOAT NOT NULL , 
     fi FLOAT NOT NULL 
    )
GO

CREATE TABLE Rejs 
    (
     ID INTEGER IDENTITY(1,1) NOT NULL , 
     start_plan DATETIME NOT NULL , 
     start_fakt DATETIME NOT NULL , 
     koniec_fakt DATETIME NOT NULL , 
     opis VARCHAR (150) , 
     Statek_ID INTEGER , 
     Port_Pocz_ID INTEGER , 
     Port_Cel_ID INTEGER , 
     koniec_plan DATETIME 
    )
GO

ALTER TABLE Rejs ADD CONSTRAINT Rejs_PK PRIMARY KEY CLUSTERED (ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE Statek 
    (
     ID INTEGER NOT NULL PRIMARY KEY, 
     nazwa VARCHAR (20) NOT NULL , 
     klasa VARCHAR (20) , 
     opis VARCHAR (150) , 
     bandera CHAR (4) 
    )
GO

CREATE TABLE Towar 
    (
     ID INTEGER NOT NULL , 
     nr_listu VARCHAR (32) , 
     nazwa VARCHAR (20) , 
     lokalizacja VARCHAR (50) , 
     ilosc DECIMAL (28) , 
     opis VARCHAR (100) , 
     Port_Pocz_ID INTEGER NOT NULL , 
     Port_Cel_ID INTEGER NOT NULL 
    )
GO

ALTER TABLE Towar ADD CONSTRAINT Towar_PK PRIMARY KEY CLUSTERED (ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE Transport_towaru 
    (
     start_plan DATETIME NOT NULL , 
     koniec_plan DATETIME NOT NULL , 
     start_fakt DATETIME , 
     koniec_fakt DATETIME , 
     lokalizacja VARCHAR (50) , 
     uwagi VARCHAR (150) , 
     Statek_ID INTEGER NOT NULL , 
     Port_Pocz_ID INTEGER , 
     Port_Cel_ID INTEGER , 
     Towar_ID INTEGER NOT NULL 
    )
GO

ALTER TABLE Transport_towaru ADD CONSTRAINT Transport_towaru_PK PRIMARY KEY CLUSTERED (Towar_ID, Statek_ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

ALTER TABLE Rejs 
    ADD CONSTRAINT Rejs_Port_Pocz_FK FOREIGN KEY 
	(Port_Pocz_ID)
    REFERENCES Port 
    ( 
	ID
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE Rejs 
    ADD CONSTRAINT Rejs_Port_Cel_FK FOREIGN KEY 
	(Port_Cel_ID)
    REFERENCES Port 
    ( 
	ID
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE Rejs 
    ADD CONSTRAINT Rejs_Statek_FK FOREIGN KEY 
	(Statek_ID)
    REFERENCES Statek 
    (ID)
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE Towar 
    ADD CONSTRAINT Towar_Port_Pocz_FK FOREIGN KEY 
    (Port_Pocz_ID)
    REFERENCES Port 
    ( 
	ID
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE Towar 
    ADD CONSTRAINT Towar_Port_Cel_FK FOREIGN KEY 
    (Port_Cel_ID)
    REFERENCES Statek 
    (ID)
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE Transport_towaru 
    ADD CONSTRAINT Transport_towaru_Port_Pocz_FK FOREIGN KEY 
    (Port_Pocz_ID)
    REFERENCES Port 
    ( ID) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE Transport_towaru 
    ADD CONSTRAINT Transport_towaru_Port_Cel_FK FOREIGN KEY 
    (Port_Cel_ID)
    REFERENCES Statek 
    (ID)
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE Transport_towaru 
    ADD CONSTRAINT Transport_towaru_Statek_FK FOREIGN KEY 
    (Statek_ID)
    REFERENCES Statek 
    ( 
	ID
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE Transport_towaru 
    ADD CONSTRAINT Transport_towaru_Towar_FK FOREIGN KEY 
    ( 
     Towar_ID
    ) 
    REFERENCES Towar 
    ( 
     ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

COMMIT

-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             5
-- CREATE INDEX                             0
-- ALTER TABLE                             12
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE DATABASE                          0
-- CREATE DEFAULT                           0
-- CREATE INDEX ON VIEW                     0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE ROLE                              0
-- CREATE RULE                              0
-- CREATE SCHEMA                            0
-- CREATE SEQUENCE                          0
-- CREATE PARTITION FUNCTION                0
-- CREATE PARTITION SCHEME                  0
-- 
-- DROP DATABASE                            0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
